url: "https://www.raygun.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "A Raygun Production" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  videos:
    output: true
  photos:
    output: true

destination: docs/

exclude:
  - templates/
  - raygun-jekyll-2024.code-workspace
